<a href="https://colab.research.google.com/github/Siddha-Regilla/Data-Science-Classroom-notebooks/blob/main/21.%20SVM_19_03_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# SVM Classification
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import SVC # Support vector classifier
from sklearn.model_selection import GridSearchCV # To select the best parameters
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score



In [ ]:
filename = '/content/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pd.read_csv(filename, names=names)
array = dataframe.values
# Divide into target and independant variables
X = array[:,0:8]
Y = array[:,8]

In [ ]:
# Divide the data into training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3, random_state = 42)

In [ ]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((537, 8), (537,), (231, 8), (231,))

### Grid Search CV

In [ ]:
clf = SVC() # The model
# We are then using RBF - radial basis function kernel, giving a list of gamma values and a list of cost values
param_grid = [{'kernel':['rbf'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
# from the above values/parameter we are using grid search CV and identifying the best parameters
gsv = GridSearchCV(clf,param_grid,cv=10)
# Fitting it on the training dataset
gsv.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['rbf']}])

In [ ]:
# Finding out the best parameters
gsv.best_params_ , gsv.best_score_

({'C': 15, 'gamma': 50, 'kernel': 'rbf'}, 0.6499301187980433)

In [ ]:
# Using the best gamma value and cost value, we build the model
clf = SVC(C= 15, gamma = 50)
# Fitting it on training dataset
clf.fit(X_train , y_train)
# Predicting on the testing dataset
y_pred = clf.predict(X_test)
# Finding out the accuracy
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 65.36796536796537


array([[151,   0],
       [ 80,   0]])

In [ ]:
# Changing the kernel to Linear
clf = SVC(kernel= "linear")
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 74.45887445887446


array([[122,  29],
       [ 30,  50]])

In [ ]:
# Chaning the kernel to poly
clf = SVC(kernel= "poly")
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 74.89177489177489


array([[133,  18],
       [ 40,  40]])

In [ ]:
# Chaning the kernel to sigmoid
clf = SVC(kernel= "sigmoid")
clf.fit(X_train , y_train)
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 53.67965367965368


array([[108,  43],
       [ 64,  16]])

In [ ]:
# Among all the kernels, Poly kernel gives the best accurarcy